USE [master]
GO

/****** Object:  Database [SlaveDB]    Script Date: 5/20/2018 2:52:17 PM ******/
CREATE DATABASE [SlaveDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SlaveDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SlaveDB.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SlaveDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SlaveDB_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SlaveDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SlaveDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SlaveDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SlaveDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SlaveDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SlaveDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SlaveDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SlaveDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SlaveDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SlaveDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SlaveDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SlaveDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SlaveDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SlaveDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SlaveDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SlaveDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SlaveDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SlaveDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SlaveDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SlaveDB] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [SlaveDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SlaveDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SlaveDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SlaveDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SlaveDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SlaveDB] SET  MULTI_USER 
GO

ALTER DATABASE [SlaveDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SlaveDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SlaveDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SlaveDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SlaveDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SlaveDB] SET QUERY_STORE = OFF
GO

USE [SlaveDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SlaveDB] SET  READ_WRITE 
GO


